### ISSUE TITLE
Setting spookfox-native-installation-dir wiped everything in that directory

### ISSUE THREAD

**Issue by ohmyhub** [bitspook/spookfox#16]
Hello!

This is an interesting package and I've been trying to set it up for the last few days.

I saw that you'd made some significant changes recently and tried setting everything up from scratch.

I set `spookfox-native-installation-dir` to `~/.local/bin/` thinking it would make things easier if I chose a directory that was already in my `$PATH`.

It successfully downloaded and installed the bin, and spookfox was working.

_**Unfortunately, it also wiped everything else that was in that directory.**_

This is not ideal.

Here are some relevant details:
Distro — **Arch Linux**
Emacs Version — **28.0.91 (Doom Emacs)**

I installed `spookfox.el` by pointing `straight.el` at this repo.

I installed the firefox add-on by using the new `xpi` file you provided.

Here is the relevant part of my emacs config:
```lisp
(setq spookfox-saved-tabs-target '(file+headline "~/Dropbox/Org/spookfox.org" "Open Tabs"))
(setq spookfox-native-installation-dir "~/.local/bin/")
```

I installed the spookfox-native bin by using the following from INSTALLATION - Step 3 in the README.

> Once spookfox.el is installed, you can call src_elisp{spookfox-install-native} interactively (by pressing M-x) in Emacs to install the final piece. Note this will only work on Linux.

Please take a minute to look into what might have caused this.

I'm looking into it on my end since it's more likely user error but there are plenty more idiots like me in the world and they might make the same mistake I did.

**Comment by bitspook** [comment]
Oh snap 😣! I am so sorry this happened to you. I will make a change to ensure we never delete entire directories. The prompt message is also somewhat misleading. I guess I got too excited that I was close to a presentable-state I made some rash decisions.

**Comment by ohmyhub** [comment]
> PS `spookfox-native` don't need to be in $PATH. It is executed by Firefox, which identifies it based on what is stored in `~/.mozilla/native-messaging-hosts/spookfox.json` file.

Ah, that's good to know.

Also, no worries. This is a neat package and I've enjoyed tinkering with it.

I've learned a valuable lesson. I should have had those scripts backed up with version control and I wasn't being cautious because I was excited to try out spookfox.

Complaining about it also made me feel better.

**Comment by bitspook** [comment]
I've made the change I mentioned; it won't bring your scripts back, but I hope someone else won't suffer a similar fate. 

Thank your trying the package out! I hope you like it. It still has some rough edges, although there shouldn't be anything as damaging. I've been using it full-time for a few days and have observed only minor inconviniences (#14  #15).
