### ISSUE TITLE
Invalid file location: nil

### ISSUE THREAD

**Issue by lytex** [bitspook/spookfox#18]
I have installed the extension and the binary following the readme, but I get this message

I've tried to toggle debug-on-error to see where the error is coming from, but I'm not getting anything.

I've seen [this line](https://github.com/bitspook/spookfox/blob/master/spookfox.el#L127) `(ignore-errors (sf--connect))` but executing without ignore-errors doesn't give an error neither.

The connection should be working as `(sf--request-active-tab)` is working and I get for example `(:chained :false :title "New Issue · bitspook/spookfox" :url "https://github.com/bitspook/spookfox/issues/new")`. Also `sf--last-faulty-pkt` is nil

**Comment by bitspook** [comment]
I assume you are getting this error when trying to save a tab (e.g on `M-x spookfox-save-active-tab` or opening a new tab in Firefox). You have already verified that spookfox can communicate with Firefox; I suppose next piece to investigage would be accessing the org file where spookfox would save tabs.

What do your `spookfox-saved-tab-target` value looks like?

**Comment by bitspook** [comment]
I've tried different iterations of setting invalid values for `spookfox-saved-tab-target` (non-existent file, non-existent directory, invalid org-capture target in other ways), but I am never getting `Invalid file location: nil` error. 
Can you also tell at what stage are you getting this error? And have you been able to replicate it or was it a one-time thing?

**Comment by bitspook** [comment]
I managed to replicate your issue. Problem was indeed with `spookfox-saved-tab-target`. Its default value (and value showed in readme.org) was using wrong kind of quotes; I've fixed it to 

    (setq spookfox-saved-tabs-target `(file+headline ,(expand-file-name "spookfox.org" org-directory) "Tabs"))` 

now, which should allow execution of `(expand-file-name "spookfox.org" org-directory)`, hence setting a valid file-location for org-capture.

Please close this issue if this fixes your problem.

**Comment by lytex** [comment]
Yep, that was it, I was using the default config
