### ISSUE TITLE
Replace spookfox-native with firefox Marionette?

### ISSUE THREAD

**Issue by QiangF** [bitspook/spookfox#23]
It looks like we can get open tabs via the marionette protocol:
https://metacpan.org/pod/Firefox::Marionette#window_handles
window_handles returns a list of top-level browsing contexts. On desktop this typically corresponds to the set of open tabs for browser windows, or the window itself for non-browser chrome windows. Each window handle is assigned by the server and is guaranteed unique, however the return array does not have a specified ordering.

There is a emacs package for that protocol
https://github.com/xuchunyang/marionette.el

**Comment by QiangF** [comment]
This one is also interesting : https://github.com/balta2ar/brotab/

**Comment by bitspook** [comment]
Thank you for sharing these @QiangF !

Marionette seems very interesting. But it seem to have a requirement of starting Firefox with a special CLI flag, which might make a worse UX. I will look more into it when I have some time to breath (kinda running hot these days), to see what advantage it has over a browser addon which uses native-messaging. 

Is there a particular concern with spookfox-native that you want resolved? 

Native messaging has a few advantages here:
1. I think it makes for a better experience; you can use Firefox as usual without any CLI flags. I personally want to use Spookfox with my normal browser; so I can interact with the web with same flexibility that Emacs allow for fs.
2. An in-browser UI is possible without hacks (not sure how easy it would be with Marionette). 
3. Arguably addon development is well defined and more popular
4. Web-extensions mean we can port the same code to Chromium (and derivatives) as well. It'll be possible to run multiple browsers (not just browser windows) and have access to same underlying tabs

One obvious advantage of using marionette probably is zero-effort portability to every platform which Firefox itself supports. 

---

brotab provides a lot of functionality to achieve what I am currently trying to achieve with Spookfox right now. But I want much more from spookfox; I want to build it such that it'll allow extending the web itself. 

Currently I am working on implementing the architecture which would allow extending Firefox addon itself from Emacs. i.e spookfox itself will act as a base which just allow communication b/w browser and Emacs, for quickly adding a UI, browser-side state management etc. It will then have extensions of its own (right now I am calling them "apps") which a user can write in Emacs at any time (i.e no need to rebuild the browser addon), load and have the desired functionality. I am halfway through implementing OrgTabs as a spookfox app.

I have a few more in mind (annotating youtube videos like org-noter does for PDF files, running tech diagnostics on a website), but in general I am paving ground for more hackable browser. I'd do it in Nyxt, but the fact that they haven't implemented ad-blocking yet tells me it might not be worth spending the effort of learning CommonLisp and Nyxt itself just yet.

We can perhaps borrow ideas from brotab on what more we can do with tabs, how they do cross-platform etc, but replacing spookfox-native with it might limit what I want to do in future.

**Comment by QiangF** [comment]
Your plan for spookfox is exiting!
Perhaps you will be interested in emacs application framework also. It's mixes emacs lisp, python and javascript, those languages are more novice friendly than rust in my opinion.
Eaf-browser is the browser using emacs application framework, it actually has ad-blocking, proxy and aria2 downloader support.
https://github.com/emacs-eaf/eaf-browser

**Comment by bitspook** [comment]
I once had a passing look at EAF but never bothered much for some reason. It seems very interesting. Thank for another great reference.

**Comment by walseb** [comment]
I have been using marionette for a few basic automations in Firefox. Here's what I learned. One issue is that when you launch Firefox with marionette support, it adds an annoying red striped graphic to the URL bar and I haven't found a way to patch it out.

Another issue is that many websites block you because Firefox reports to them that you are using marionette, and so are likely to be a bot.

That can be fixed by patching Firefox like this:
```diff
diff --git a/dom/base/Navigator.cpp b/dom/base/Navigator.cpp
index 85340db5dc..acc576a890 100644
--- a/dom/base/Navigator.cpp
+++ b/dom/base/Navigator.cpp
@@ -2259,26 +2259,6 @@ dom::LockManager* Navigator::Locks() {
 
 /* static */
 bool Navigator::Webdriver() {
-#ifdef ENABLE_WEBDRIVER
-  nsCOMPtr<nsIMarionette> marionette = do_GetService(NS_MARIONETTE_CONTRACTID);
-  if (marionette) {
-    bool marionetteRunning = false;
-    marionette->GetRunning(&marionetteRunning);
-    if (marionetteRunning) {
-      return true;
-    }
-  }
-
-  nsCOMPtr<nsIRemoteAgent> agent = do_GetService(NS_REMOTEAGENT_CONTRACTID);
-  if (agent) {
-    bool remoteAgentRunning = false;
-    agent->GetRunning(&remoteAgentRunning);
-    if (remoteAgentRunning) {
-      return true;
-    }
-  }
-#endif
-
   return false;
 }
```

However, this requires a rebuild of Firefox on Nixos, and the build times are extremely long, so I eventually stopped doing this.

The marionette API didn't have great documentation, but it had most features I was looking for.
