### ISSUE TITLE
Action initiated by firefox

### ISSUE THREAD

**Issue by nico202** [bitspook/spookfox#29]
Hi, thanks for creating this!
I'm automating part of my firefox use with spookfox (e.g., copying doodles dates to org-mode), but a thing I'm missing is the ability to trigger actions from firefox.
I was wondering if right now it is possible to have a bookmarklet of some sort which calls some spookfox addons code, which calls an emacs function.
For example, I'd like to have an "org-capture".  In emacs a function would choose a different capture template based on the url I'm at, eventually call some js to extract required data/act on the page.  Right now I have to manually switch to emacs and trigger the capture from there.
Any hint on where to start? (I'm not even sure bookmarklets can access addons' code)
Thanks!

**Comment by bitspook** [comment]
>  trigger actions from firefox

This isn't possible right now. I mean it is, but there is no UI for this. 

One way to achieve what you want is if Spookfox has the ability to send custom actions/requests to Emacs on e.g a user-defined keyboard shortcut. I created [this branch](https://github.com/bitspook/spookfox/compare/master...send-custom-messages-to-emacs-on-keypress) for this purpose, but couldn't finish it in a couple hours. You can check [this commit](https://github.com/bitspook/spookfox/commit/a0b65f64b33690a8e02a826aa7c86701444146da) for challenges I am facing for this. 

If you have ideas on how else we can achieve your use-case, please feel free to suggest. If you want to hack on Spookfox yourself, I'll be more than happy to help. Just say the word! 

In the meanwhile, I'll keep this issue open until this feature is developed. You can keep track using the [linked branch](https://github.com/bitspook/spookfox/tree/send-custom-messages-to-emacs-on-keypress).

**Comment by bitspook** [comment]
I had a change of mind. You already gave me a great idea, but I started implementing a limited version of it. But I pivoted back and have added the ability to send custom requests to Emacs. 

You can now create a Javascript bookmarklet and run any elisp corresponding to that. Here's the snippet from the [docs](https://bitspook.in/projects/spookfox/):

---
4. Register custom request handlers

   It is possible to send custom events from browser (e.g using a JavaScript
   bookmarklet), and run elisp code to handle them. For this you need to do 2
   things:

   1. Add a handle for request in Emacs

      Here is some example code for registering a request handler:

     ```lisp
        (defun my--capture-the-flag (url)
          (message "CAPTURING THE FLAG: %s" url))

        (spookfox--register-req-handler "CAPTURE_THE_FLAG" #'my--capture-the-flag)
      ```
   2. Send a request from browser

      ```js
        postMessage({
          type: 'SPOOKFOX_RELAY_TO_EMACS',
          action: {
            name: 'CAPTURE_THE_FLAG',
            payload: { url: window.location.href }
          }
        })
      ```

      =action= part here decides which request handler will execute. Elisp
      version of =payload= will be provided to your request-handler as an
      argument.
```
---

I've tested by running above elisp in my Emacs (v28.2), and making a js bookmarklet for above JS. It works as expected for me. If you face any problems, do let me know.

Thank you for creating this issue!

**Comment by nico202** [comment]
Ok finally I had a few minutes to try this out and that's *exactly* what I meant :) Many thanks, hopefully I'll be able to share something useful coming out from this, I see a lot of possibilities
