### ISSUE TITLE
Suggestion: Rename `sfjsi-eval-in-active-tab` to `sfjsi-eval-in-active-tabs` (note the s at the end)

### ISSUE THREAD

**Issue by rodrigomorales1** [bitspook/spookfox#37]
https://github.com/bitspook/spookfox/blob/ee4f23f022db70e8ad3b057140c75a17a3df6dab/lisp/apps/spookfox-js-injection.el#L19-L24

I inspected the source code and I noticed that what master branch is currently referring to as "active tab" is actually "active tabs". This is how we are currently getting the "active tabs". For this reason, I believe it would be more accurate to rename `sfjsi-eval-in-active-tab` to `sfjsi-eval-in-active-tabs`.

https://github.com/bitspook/spookfox/blob/ee4f23f022db70e8ad3b057140c75a17a3df6dab/spookfox-addon/src/apps/JsInject.ts#L34

https://github.com/bitspook/spookfox/blob/ee4f23f022db70e8ad3b057140c75a17a3df6dab/spookfox-addon/src/apps/JsInject.ts#L42

When I used this package for the first time, I evaluated `window.location = 'https://example.org/'` which changes the current URL of the active tab. I had many Firefox windows opened, so that code was executed on the active tab in all Firefox windows which visited `https://example.org/`,

**Comment by bitspook** [comment]
Thanks a lot for reporting this @rodrigomorales1! I agree, this function can be named better. Multiple windows in general need better handling. I'll try to give some time to improving multi-window handling this week, or if I fail, I'll at least rename this function. Will keep you posted.
Thanks again!

**Comment by bitspook** [comment]
Hello @rodrigomorales1,

I decided to fix the behavior of `spookfox-js-injection-eval-in-active-tab` instead. Its purpose is to run js in the active tab for quick tinkering (e.g get current tab's URL to put in notes). The fact that it runs js in active-tab per window is a bug. This is emphasized by the presence of `just-the-tip-p` argument, which returns the results returned by js from first tab.

This function now uses `[browser.windows.getCurrent](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/getCurrent)` to first determine the window whose active-tab should be worked with. 

I am closing this issue, but please feel free to reopen if you'd prefer a different resolution.
