### ISSUE TITLE
Rename `Action` and `ActionResponse` to `Request` and `Response`

### ISSUE THREAD

**Issue by bitspook** [bitspook/spookfox#9]
Somehow I reached the point where I had made the choice of dividing messages
over socket into \`Action\` and \`ActionResponse\`. \`Request\` and \`Response\` seem
more appropriate. I am deferring that for now, so to get the real features built
while I have the momentum.

**Comment by msanfilippof** [comment]
@bitspook can I take it?

**Comment by bitspook** [comment]
Definitely!
